apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo-be-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoo-be-pod
  template:
    metadata:
      labels:
        app: zoo-be-pod
    spec: 
      containers:
      - name: zoo-be-container
        image: rameshll/zoo-be:v1
  
---
apiVersion: v1
kind: Service
metadata:
  name: zoo-be-service
spec:
  type: LoadBalancer
  selector:
    app: zoo-be-pod
  ports:
  - protocol: TCP
    targetPort: 2000
    port: 2000



