apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo-be-deployment
spec:
  selector:
    matchLabels:
      app: zoo-be-app
  replicas: 2
  template:
    metadata:
      labels:
        app: zoo-be-app
    spec:
      containers:
        - name: zoo-be
          image:  rameshll/zoo-be:v1
        - name: zoo-fe
          image: rameshll/zoo-fe:v1

             
      
          